//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        public int SubCategoryID { get; set; }
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string CreatedByUserId { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public string LasUpdatedByUserId { get; set; }
        public System.DateTime LastUpdatedOnDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
